# Generated by Django 2.0.6 on 2018-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Department',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
