# Generated by Django 2.0.6 on 2018-07-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180718_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=500, null=True)),
                ('Location', models.CharField(max_length=500, null=True)),
                ('job_title', models.CharField(max_length=500, null=True)),
                ('job_description', models.TextField(max_length=500, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='mypics/%Y/%m/%d')),
                ('Company_email', models.EmailField(max_length=254)),
                ('JobNature', models.CharField(choices=[('Full Time', 'FUll Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern')], max_length=15)),
                ('Salary', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
