# Generated by Django 2.0.6 on 2018-07-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, null=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Company')),
            ],
        ),
    ]
