# Generated by Django 2.0.6 on 2018-07-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_jobsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='JobNature',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern')], max_length=15),
        ),
    ]
