# Generated by Django 2.0.6 on 2018-07-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20180719_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(blank=True, default='mypics/noimage.png', upload_to='mypics/%Y/%m/%d'),
        ),
    ]
