# Generated by Django 2.0.6 on 2018-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20180720_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
