# Generated by Django 2.0.6 on 2018-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20180721_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Companyname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
