# Generated by Django 2.0.6 on 2018-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20180721_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(blank=True, null='True', upload_to='mypics/%Y/%m/%d'),
        ),
    ]
