# Generated by Django 2.0.6 on 2018-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20180721_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(null='True', upload_to='mypics/%Y/%m/%d'),
        ),
    ]
