# Generated by Django 2.0.6 on 2018-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_auto_20180721_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(null='True', upload_to='mypics/%Y/%m/%d'),
        ),
    ]
