# Generated by Django 2.0.6 on 2018-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_auto_20180827_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='mypics/%Y/%m/%d'),
        ),
    ]
