# Generated by Django 2.0.6 on 2018-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_auto_20180827_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_by', models.EmailField(max_length=100)),
                ('Send_to', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
    ]
