# Generated by Django 2.0.6 on 2018-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Send_by',
            new_name='Applier_email',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Send_to',
            new_name='Company_email',
        ),
    ]
