# Generated by Django 2.0.6 on 2018-08-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20180827_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(null=True, upload_to='mypics/%Y/%m/%d'),
        ),
    ]
