# Generated by Django 2.0.6 on 2018-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_auto_20180828_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Image',
            field=models.ImageField(blank=True, default='../img/noimage.png', null=True, upload_to='mypics/%Y/%m/%d'),
        ),
    ]
